# Generated by Django 4.0.3 on 2022-03-23 11:08

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('is_manager', models.BooleanField(default=False)),
                ('is_chef', models.BooleanField(default=False)),
                ('is_waiter', models.BooleanField(default=False)),
                ('is_customer', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='chef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Phone_no', models.IntegerField()),
                ('Address', models.TextField(max_length=100)),
                ('Qualification', models.CharField(max_length=100)),
                ('Experience', models.IntegerField()),
                ('specialisation', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Phone_no', models.IntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Rtable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Table_no', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Table_no', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='waiter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Phone_no', models.IntegerField()),
                ('Address', models.TextField(max_length=100)),
                ('Experience', models.IntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='table_order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('expected_time', models.TimeField()),
                ('t_status', models.IntegerField(default=0)),
                ('torder_status', models.IntegerField(default=0)),
                ('tpay_status', models.IntegerField(default=0)),
                ('tdelivered_status', models.IntegerField(default=0)),
                ('c', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rest_app.chef')),
                ('custom', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rest_app.customer')),
                ('table_no', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rest_app.table')),
                ('w', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rest_app.waiter')),
            ],
        ),
        migrations.CreateModel(
            name='incre_req',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incredients', models.TextField(max_length=100)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('in_status', models.IntegerField(default=0)),
                ('ch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rest_app.chef')),
            ],
        ),
        migrations.CreateModel(
            name='food_order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FoodName', models.CharField(max_length=100, null=True)),
                ('food_type', models.CharField(max_length=200, null=True)),
                ('table_no', models.IntegerField(default=0)),
                ('phone', models.IntegerField(null=True)),
                ('Price', models.IntegerField(null=True)),
                ('cardnumber', models.IntegerField(null=True)),
                ('cvv', models.IntegerField(null=True)),
                ('date', models.DateField()),
                ('food_status', models.IntegerField(default=0)),
                ('waiter_status', models.IntegerField(default=0)),
                ('order_status', models.IntegerField(default=0)),
                ('pay_status', models.IntegerField(default=0)),
                ('delivered_status', models.IntegerField(default=0)),
                ('c', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rest_app.chef')),
                ('custom', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rest_app.customer')),
                ('w', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rest_app.waiter')),
            ],
        ),
        migrations.CreateModel(
            name='food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FoodName', models.CharField(max_length=100)),
                ('pic', models.FileField(upload_to='pics')),
                ('food_type', models.CharField(max_length=200)),
                ('food_category', models.CharField(max_length=200)),
                ('Price', models.IntegerField()),
                ('food_status', models.IntegerField(default=0)),
                ('waiter_status', models.IntegerField(default=0)),
                ('order_status', models.IntegerField(default=0)),
                ('delivered_status', models.IntegerField(default=0)),
                ('c', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rest_app.chef')),
                ('custom', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rest_app.customer')),
                ('w', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rest_app.waiter')),
            ],
        ),
    ]
